spring:
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    platform: h2
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true #data.sql 적용(?)하기 위한 구문
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      connection:
        charSet: UTF-8
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5e233018103409a275aad30214d4daba
            client-secret: hzkliB8UlgxSfGQ4rwGxJqvl0DnF93tS
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id