spring:
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    platform: h2
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
      connection:
        charSet: UTF-8

#Jwt
mail:
  address:
    admin: admin@gmail.com
jwt:
  secret-key:  c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420